name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: List directory contents
        run: |
          echo "Listing current directory:"
          ls -la
          echo "Listing CarDealership directory:"
          ls -la CarDealership  # Adjust if your project is in a different folder

      - name: Restore dependencies
        run: dotnet restore CarDealership/CarDealership.csproj  # Update if the path is incorrect

      - name: Build the project
        run: dotnet build CarDealership/CarDealership.csproj --configuration Release --no-restore  # Update if the path is incorrect
