name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Latest version

      - name: Setup .NET
        uses: actions/setup-dotnet@v3  # Updated to the latest version
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore CarDealership.sln

      - name: Build project
        run: dotnet build CarDealership.sln --configuration Release --no-restore

      - name: Publish artifacts
        run: dotnet publish CarDealership.sln --configuration Release --output ./output

  # ... (rest of your workflow)
