name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is updated

      - name: Setup .NET
        uses: actions/setup-dotnet@v3  # Ensure this is updated
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore CarDealership.sln

      - name: Build project
        run: dotnet build CarDealership.sln --configuration Release --no-restore

      - name: Publish artifacts
        run: dotnet publish CarDealership.sln --configuration Release --output ./output

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is updated

      - name: Setup .NET
        uses: actions/setup-dotnet@v3  # Ensure this is updated
        with:
          dotnet-version: '6.0.x'

      - name: Run unit tests
        run: dotnet test CarDealership.Tests/CarDealership.Tests.csproj --configuration Release --collect:"XPlat Code Coverage"

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is updated

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment..."
          az webapp deploy --resource-group your-resource-group --name your-webapp-name --src-path ./output
